//> using scala 2.13
//> using toolkit typelevel:0.1.26
//> using plugin org.typelevel:::kind-projector:0.13.3
//> using resourceDir resources
//> using dep org.rudogma::supertagged:2.0-RC2
//> using dep org.typelevel::log4cats-slf4j:2.7.0
//> using dep ch.qos.logback:logback-classic:1.5.6
//> using dep io.circe::circe-fs2:0.14.1
//> using dep io.circe::circe-parser:0.14.7
